grep -ir "events" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "tracks" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "trackppt" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "trackdxy" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "trackerhits" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "trackerchi2" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "trackertidtec" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "minnchambers" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "totchambers" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'

grep -ir "station123" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station123valid" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station123dt13hits" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station123dt2hits" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station123aligning" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "resslopey" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'

grep -ir "station4" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station4valid" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station4hits" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "station4aligning" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'

grep -ir "csc" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "cscvalid" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "cschits" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
grep -ir "cscaligning" LSFJOB* | grep COUNT | awk '{print $3}' | awk '{ SUM += $1} END { print SUM }'
